version: '2'
services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "8080:80"
    command: 
        - /bin/sh
        - -c
        - |
            cat <<EOT > /etc/nginx/conf.d/default.conf
            server {
              listen 80;
              server_name  certproof.nchc.org.tw;
              location /oid/v1/ {
                proxy_pass http://oidcb/;
              }
            }
            EOT
            sleep 3
            nginx -g "daemon off;"
  oidcb:
    image: nginx:1.13-alpine
    ports:
      - "8081:80"
    command: 
        - /bin/sh
        - -c
        - |
            cat <<EOT > /usr/share/nginx/html/index.html
            <HTML>
            <BODY>
            <H1>HELLO OPENID SERVICE</H1>
            <H4>Service from oidcb container</H4>
            <BODY>
            <HTML>
            EOT
            sleep 3
            nginx -g "daemon off;"